### ISSUE TITLE
server won't start on `./launch_server.sh`

### ISSUE THREAD

**Issue by chegeiser** [inouire/baggle-server-deploy#1]
I'm trying to start a B@ggle server on a raspberry pi. I've installed JRE 1.8 and Git. I first tried with the OpedJDK install, since that didn't work I installed the Oracle JDK which resulted in the Pi running JRE 1.8.0

On `./launch_server.sh` I get this:
```
No argument specified, using default config file conf/server-default.xml
B@ggle server version 3.6.2
Use --help option to know more about the provided options
2020-04-07 10:55:21,138 - INFO  - Loading server configuration
Exception in thread "main" java.lang.NullPointerException
        at inouire.basics.myml.MyMl.loadContent(MyMl.java:164)
        at inouire.basics.myml.MyMl.loadFile(MyMl.java:199)
        at inouire.baggle.server.ServerConfiguration.loadFromFile(ServerConfiguration.java:76)
        at inouire.baggle.server.Main.main(Main.java:81)
```
I don't know how to resolve this. Any chance you can help?

Thank you!

**Comment by inouire** [comment]
@chegeiser Thanks for the feedback, I'll have a look and tell you a way to fix it

**Comment by inouire** [comment]
@chegeiser can you try launching it with  `java -jar bin/baggle-server-3.6.jar` instead ?

**Comment by chegeiser** [comment]
This worked. I'm able to get it up and running on my Windows computer. I can only access it on the local network though. 

I have not been able to figure out how to get it open to others (my family in other cities).

**Comment by chegeiser** [comment]
Wait!  ;-)  It seems it just took a bit for it to show up - it is now on the public feed.

**Comment by inouire** [comment]
cool !

**Comment by chegeiser** [comment]
Thank you for this! It's super cool to set up a b@ggle server for my family to play.

**Comment by chegeiser** [comment]
I've tried modifying the config file and it if I change the `name`, `welcomeMessage` and `language` it still works. But if I change `bigBoard: no` to `bigBoard: yes` then when I try to play the game it fails. 

The console where I typed `java -jar bin/baggle-server.jar` also give an error:
```
java.lang.NullPointerException
        at inouire.baggle.solver.GameBoard.getDice(GameBoard.java:149)
        at inouire.baggle.solver.GameBoard.toString(GameBoard.java:172)
        at inouire.baggle.solver.GameBoard.mixBoard(GameBoard.java:145)
        at inouire.baggle.server.core.GameThread.run(GameThread.java:106)
```
This error is repeated many times and then it finally shows:
```
java.lang.NullPointerException
```

Any ideas what is causing this?

This happens when I deploy from a windows machine running Java 1.8.0_241 and on a Raspberry Pi (debian) running Java 1.8.0_212-b10. Log file is attached.

Also, for some reason there are two copies of my server up and running in the salon. I'm running the 'Covintine Baggle' server.

Thanks!
[Covintine-B@ggle.log](https://github.com/inouire/baggle-server-deploy/files/4525602/Covintine-B%40ggle.log)

**Comment by inouire** [comment]
@chegeiser sorry I didn't see your reply...

Is your board is configured in english ?
